name: 'Body Issue Parser'
description: 'Scans a given body text (typically from PR) and returns any that need to be closed'
author: "Trey Gracyalny"
inputs:
  body:
    description: "Body containing references to Closed Issues"
    required: true
outputs:
  item:
    description: "Array of Issue Id's located inside given body"
runs:
  using: "node20"
  main: "dist/index.js"
