on: [push]

jobs:
  parse-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Parse PR for any Closed Issues
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: tgracyalny-jones/pr-body-parser@main
        id: issues
        with:
          body: 'Closes #1 Closes #2'
      - name: Close issues
        run: | 
          echo "${{ steps.issues.outputs.item }}"
          for issue in "$issues";
          do
            gh issue close --comment "Auto-closing issue" "$issue"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}