on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: tgracyalny-jones/pr-body-parser@main # Uses an action in the root directory
        id: issues
        with:
          body: 'Closes #1'
      # Use the output from the `hello` step
      - name: Close issues
        run: | 
          for conversation in ${{ steps.issues.outputs.item }};
          echo "$conversation[0]"
          echo "$conversation[1]"
          do
            if [ $conversation[1] == "Closes"]; then
              gh issue close --comment "Auto-closing issue" $conversation[0]
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}