on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: tgracyalny-jones/pr-body-parser@main # Uses an action in the root directory
        id: hello
        with:
          body: 'Closes #1'
      # Use the output from the `hello` step
      - name: Close issues
        run: | 
          echo ISSUES ='${{ steps.hello.outputs.item }}' | jq '.[] | if .action == "Closes" then ".issue" else "" end'
          echo "Issues: $ISSUES"

          for i in $ISSUES
          do
            gh issue close --comment "Auto-closing issue" i
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}