on: [push]

jobs:
  parse-pr:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Parse PR for any Closed Issues
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse Body
        uses: tgracyalny-jones/body-issue-parser@v1.0
        id: issues
        with:
          body: 'Closes #1 Closes #2'
      - name: Close issues
        run: | 
          issues=($(echo "${{ steps.custom.outputs.issues }}" | jq -r '.[]'))
          if issues != []; then
            for issue in "$issues";
            do
              gh issue close --comment "Auto-closing issue" "$issue"
            done
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}