on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: tgracyalny-jones/pr-body-parser@main # Uses an action in the root directory
        id: hello
        with:
          body: 'Closes #1'
      # Use the output from the `hello` step
      - name: Get Issues
        id: issues
        run: |
          echo "items=${{ steps.hello.outputs.item }} | jq -c '.[]'" >> $GITHUB_OUTPUT
      - name: Close issues
        run: | 
          echo ${{ steps.issues.outputs.items }}

          readarray -t conversations < <(${{ steps.hello.outputs.item }} | jq -c '.[]')
          echo $conversations

          for conversation in ${{ steps.hello.outputs.item }} | jq -c '.[]'; 
          do
            echo $conversation
            if [ $conversation.action == "Closes"]; then
              gh issue close --comment "Auto-closing issue" "$conversation.issue"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}