on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        uses: tgracyalny-jones/pr-body-parser@main # Uses an action in the root directory
        id: issues
        with:
          body: 'Closes #1'
      # Use the output from the `hello` step
      - name: Close issues
        run: | 
          text=$(echo "${{ fromJSON(steps.issues.outputs.item) }}" | sed 's/\[/ [ /g; s/]/ ] /g;')
          echo ${text}
          echo ${text[0]}
          echo ${text[0][0]}
          for issue in $text;
          do
            if [ $issue[1] == "Closes" ]; then
              echo ${issue[1]}
              gh issue close --comment "Auto-closing issue" $issue[0]
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}